#!/usr/bin/env bash
taskdir="$HOME/rcn/bea_res/Data/Tasks/AntiState/Basic/"
demofile=txt/demographicFromSQL.txt
subjroot="/Volumes/Governator/ANTISTATELONG/"
ofroot="$(cd $(dirname $0)/..;pwd)"
# sub001	051201162924	15.1184	M	10186	20051201	2005-12-01 00:00:00	1990-10-19 00:00:00
while read ofid bircid age sex lunaid visitdate rest; do
 ofsavedir=$ofroot/$ofid/

 subjdir=$subjroot/${lunaid}/$bircid/
 mprage=$subjdir/mprage/mprage.nii.gz

 [ ! -r "$mprage" ] && echo "$lunaid $mprage DNE!" && continue


 # get the run orders
 read ro1 ro2 ro3 ro4 <<<$(grep $bircid txt/subjOrders.txt| cut -f 2-)

 # make sure they exist
 [ -z "$ro4" ] && echo "run orders unknown for at least one in $bircid txt/subjOrdrs.txt" && continue;

 for rn in 1 2 3 4; do
  oftaskdir=antistate_$(printf %03d $rn)
  ## files
  # generated by parsing subject xls hand scored. have automatic scored too-- not used
  scorefile="$taskdir/$lunaid/$visitdate/Scored/txt/$lunaid.$visitdate.$rn.manual.txt"
  # where to find the MR data
  rundir=$subjdir/run$rn

  ## check everything exists
  [ ! -d $rundir ] && echo "$lunaid run$rn DNE!" && continue
  [ ! -r $rundir/functional.nii.gz ] && echo "$lunaid:$rn has no functional.nii.gz!" && continue;
  [ ! -r $scorefile ] && echo "$lunaid:$rn not scored? $scorefile" && continue

  ## what will we make
  bolddir=$ofsavedir/BOLD/$oftaskdir/
  behavedir=$ofsavedir/behav/$oftaskdir/
  behavdata=$behavedir/behavdata.txt

  [ ! -d "$bolddir" ] && mkdir -p $bolddir 
  [ ! -d "$behavedir" ] && mkdir -p $behavedir 

  [ ! -r "$bolddir/bold.nii.gz" ] && ln -s $rundir/functional.nii.gz $bolddir/bold.nii.gz



  # if we want to redo the behav txt file create, comment this line
  #[ -r "$behavdata" ] && continue


  # translate subject+run into a run type (01AV - 12VA )
  # find the cumulative timing for each trial
  runro=ro$rn; runtype=${!runro}
  [ $(egrep "^$runtype" txt/listOrders.txt -c) -ne 24 ] && echo "$lunaid:$rn $runtype does not have 12 trials!" && continue



  # remove scorer from score file and paste onto order
  #
  # will be like
  # 1 1  583   10AV  43.5  45 ANTICUE  108
  echo "trial score lat(ms) runtype onset(s) end(s) trialtype cuepos" > "$behavdata"
  paste <(sed 1d $scorefile) <(egrep "^$runtype" txt/listOrders.txt) | sed "s/	/ /g" >> "$behavdata"


 done


 # now that everything else worked
 # get the mprage into open fmri format
 anatdir=$ofsavedir/anatomy/
 [ ! -d "$anatdir" ] && mkdir -p $anatdir 
 [ ! -r $anatdir/highres001.nii.gz ] && ln -s $mprage $anatdir/highres001.nii.gz;


done < $demofile
